### ISSUE TITLE
error with Gulp Build Process

### ISSUE THREAD

**Issue by sak55** [sak55/skedaddle#6]
``````
Sam at Sams-MacBook-Air in ~/Sites/skedaddle/src/app (feature/turn-codes-to-names●)
$ gulp build
[16:52:52] Working directory changed to ~/Sites/skedaddle
[16:52:53] Using gulpfile ~/Sites/skedaddle/gulpfile.js
[16:52:53] Starting 'styles'...
[16:52:54] Starting 'partials'...
[16:52:54] Starting 'images'...
[16:52:54] Starting 'fonts'...
[16:52:54] Starting 'misc'...
[16:52:54] gulp-inject Nothing to inject into index.scss.
[16:52:55] Finished 'misc' after 173 ms
[16:52:55] Finished 'partials' after 924 ms
[16:52:55] Finished 'fonts' after 424 ms
[16:52:55] Finished 'images' after 459 ms
[16:52:55] Finished 'styles' after 1.75 s
[16:52:55] Starting 'inject'...
[16:52:55] gulp-inject 1 files into 404.html.
[16:52:55] gulp-inject 1 files into index.html.
[16:52:55] gulp-inject 7 files into 404.html.
[16:52:55] gulp-inject 7 files into index.html.
[16:52:55] Finished 'inject' after 398 ms
[16:52:55] Starting 'html'...
[16:52:57] gulp-inject 1 files into 404.html.
[16:52:57] gulp-inject 1 files into index.html.

/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399
        throw new Error('Please check the validity of the CSS block starting f
              ^
Error: Please check the validity of the CSS block starting from the line #5128
    at throwError (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399:15)
    at getBlock (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:755:18)
    at getAtruleb (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:632:34)
    at getAtrule (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:606:28)
    at getStylesheet (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:1937:60)
    at Object.CSSPRules.stylesheet (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:365:69)
    at _getAST (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:409:38)
    at exports.srcToCSSP (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:2287:16)
    at Object.exports.srcToCSSP (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:2292:16)
    at exports.parse (/Users/Sam/Sites/skedaddle/node_modules/gulp-csso/node_modules/csso/lib/cssoapi.js:7:21)```
``````

**Comment by sak55** [comment]
- [x] posted error
